defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/ernoaapa/linux-packages

version: 2
jobs:
  linuxkit_test:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run: ./linuxkit/bin/install-tools.sh

      - run:
          name: Build linuxkit package images
          command: |
            cd linuxkit/pkg
            make forcebuild

  linuxkit_publish:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Login Docker hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
    
      - run: ./linuxkit/bin/install-tools.sh

      - run:
          name: Build & push linuxkit package images
          command: |
            cd linuxkit/pkg
            make forcepush

  packages_test:
    <<: *defaults
    steps:
      - checkout

      - run: ./packages/bin/install-tools.sh

      - run:
          name: build & release Linux packages
          command: GOOS=linux GOARCH=amd64 ./packages/build-all.sh

  packages_publish:
    <<: *defaults
    steps:
      - checkout

      - run: ./packages/bin/install-tools.sh

      - run:
          name: build & release Linux packages
          command: GOOS=linux GOARCH=amd64 ./packages/publish-all.sh

workflows:
  version: 2
  linuxkit-build-and-publish:
    jobs:
      - linuxkit_test

      - linuxkit_publish:
          requires:
            - linuxkit_test

  packages-build-and-publish:
    jobs:
      - packages_test
      - packages_publish:
          requires:
            - packages_test
